### ISSUE TITLE
InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag

### ISSUE THREAD

**Issue by mikecollard** [SonarQubeCommunity/sonar-build-breaker#12]
Installed plugin with SonarQube 5.4
Default plugin configuration
Getting:

com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag

Also reported by another user in comment here:

http://stackoverflow.com/questions/36885064/how-to-use-the-build-breaker-on-sonarqube-5-1-if-a-project-quality-gate-fails

**Comment by mikecollard** [comment]
Full stack:

Caused by: org.apache.maven.plugin.MojoExecutionException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at org.sonarsource.scanner.maven.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:36)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:81)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalStateException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:155)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.execute(QualityGateBreaker.java:108)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.executeOn(QualityGateBreaker.java:95)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55)
	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:113)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:264)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:259)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:249)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.batch.scan.ProjectScanContainer.startComponents(ProjectScanContainer.java:127)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy16.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78)
	... 22 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:70)
	at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1082)
	at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1149)
	at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:778)
	at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:770)
	at com.google.protobuf.CodedInputStream.readInt64(CodedInputStream.java:343)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:510)
	at com.google.protobuf.GeneratedMessage.parseUnknownField(GeneratedMessage.java:276)
	at org.sonarqube.ws.WsCe$TaskResponse.<init>(WsCe.java:816)
	at org.sonarqube.ws.WsCe$TaskResponse.<init>(WsCe.java:784)
	at org.sonarqube.ws.WsCe$TaskResponse$1.parsePartialFrom(WsCe.java:1249)
	at org.sonarqube.ws.WsCe$TaskResponse$1.parsePartialFrom(WsCe.java:1243)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.sonarqube.ws.WsCe$TaskResponse.parseFrom(WsCe.java:938)
	at org.sonar.plugins.buildbreaker.QualityGateBreaker.getAnalysisId(QualityGateBreaker.java:138)
	... 52 more

**Comment by mjdetullio** [comment]
This plugin is compiled against the 5.3 Profobuf API and nothing in the `WsCe` proto changed between 5.3 and 5.4.  Even if there were changes, protos are backwards compatible.

I've also tested the latest version of this plugin against every released version of SonarQube 5.3 and newer without issue.

The most likely scenario is the data was corrupted in transit from the server to the scanner.  Or your server or some intermediary is mangling responses.

If this is highly reproducible you should investigate at a lower level by attempting to get the raw response data from the SQ server appliance and then comparing it with the same raw data received by the scanner.

**Comment by mikecollard** [comment]
Happens every time without exception so I don't think it is a transport issue.
Other user referenced the same issue so I am not alone.

**Comment by mjdetullio** [comment]
Again, because I can't reproduce this, it will require more investigation
and fix if necessary on your part.

Network problems are so common that I hardly consider one other documented
case of a protobuf error a bug in the code.

**Comment by fjakop** [comment]
This seems to be no issue with the plugin, but a misconfiguration of your SQ instance.
I was able to reproduce this reliably when I set "Server base URL" (`sonar.core.serverBaseURL`) to an url not matching the server's url.
In my case I replicated my production SQ instance to a test server and did not adapt this setting.
